### PR TITLE
Support Ruby profiling on Windows

### PR DESCRIPTION
**Pull request by lowjoel**
:)

I have not tested this on Linux, since I'm currently on a Windows machine, but it should work.

It might concern you that I'm using SIGINT on Windows, but on the MSVC runtime (which Mingw uses too) SIGINT is not used by the system. I cannot use SIGALRM because Windows does not have that signal defined, and attempting to use it would cause a parameter validation error in the runtime.

capture

### CODE REVIEW

**Comment by lowjoel** [comment]
@tgxworld in case you're interested in how I did it...

**Comment by SamSaffron** [comment]
I am fine to merge this, but do you mind taking over publishing gems here,
doing the multi build with windows kind of scares me.

**Comment by lowjoel** [comment]
Thanks Same, what do you mean by publishing? As in pushing them to rubygems?

**Comment by SamSaffron** [comment]
Yeah, I can give you commit on the repo + add you to authors and you can
take care of publishing this thing :) plus be a co maintainer, keep in mind
on 2.2 I usually use stack prof in raw mode.

**Comment by lowjoel** [comment]
Sure.

I'd use stackprof, but there seems to be even more that I need to wire up for Windows to get rack-mini-profiler working, so I figured I should get this working first since it's a simpler implementation.

Maybe in future I'll be able to port stackprof to Windows too...

**Comment by SamSaffron** [comment]
can you pm me your email address my twitter handle is @samsaffron, that way
I can give you ownership on the gem? I just added you as collaborator, if
you are 100% this all works please merge.

**Comment by lowjoel** [comment]
My email is the same as the one on my profile (should be publicly displayable)

**Comment by SamSaffron** [comment]
np, you are an owner on fast_stack now !

**Comment by lowjoel** [comment]
@SamSaffron can you enable Travis for this repo? I'd want to get it working.

Also, AppVeyor for Windows once I get around to doing that...

**Comment by SamSaffron** [comment]
Go for it :) I thought you have commit ...

**Comment by lowjoel** [comment]
It appears that Travis doesn't let me activate it for a repo unless I have admin, so I don't get to turn it on.

**Comment by SamSaffron** [comment]
hmmm it appears to be active on fast stack ...

**Comment by lowjoel** [comment]
Yup, it is, I’ll work on it.

**Pull request merged**
